# Site settings
title:          Values
description:    "Welcome to Yesterday"
baseurl:        "/Values"
url:            "https://majuntang.com/Values/"

# Author
author:
  name:         Ma Juntang
  url:          https://majuntang.com
  email:        me@vrolia.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
